# default: &default
#   dispatchers:
#     - polling_interval: 1
#       batch_size: 500
#   workers:
#     - queues: "*"
#       threads: 3
#       processes: 1
#       polling_interval: 0.1
#
development:
  workers:
    - queues: [high, default, low]
      threads: 3
#
# test:
#  <<: *default
#
# production:
#  <<: *default
