name: judoscale-delayed_job tests
defaults:
  run:
    working-directory: judoscale-delayed_job
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - Gemfile
          - Gemfile-activerecord-7-0
          - Gemfile-activerecord-6-1
        ruby:
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
        exclude:
          - gemfile: Gemfile
            ruby: "2.6"
          - gemfile: Gemfile-activerecord-7-0
            ruby: "2.6"
    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/judoscale-delayed_job/${{ matrix.gemfile }}
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs bundle install and caches installed gems automatically
      - run: bundle exec rake
