name: Lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: gem install standard
      - run: standardrb
