name: release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: Create a release
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Release
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: ruby
          package-name: release-please-action
          bump-minor-pre-major: true
          version-file: "judoscale-ruby/lib/judoscale/version.rb"

      - name: Sync versions - checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.release.outputs.pr.headBranchName }}

      - name: Sync versions - setup Ruby
        if: ${{ steps.release.outputs.release_created }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Sync versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          bin/sync-versions
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Sync versions"
          git push

  publish:
    name: Publish to Rubygems
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release_created == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Publish gems
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
        run: bin/release
